s = 'salam'
print (len(s))
s2 =s.capitalize()
print(s, s2)
print (s.center(20, '!'))
print (s. count('l', 0,4))
print (s.find('l'))
print (s.index('l'))
print (s.replace('l', 't'))
print (s.split(','))
print (s.isdigit())
print (s.isalpha())